# https://pub.dev/packages/yumemi_lints
include: package:yumemi_lints/flutter/3.19.0/recommended.yaml

# `freezed` が生成したファイルを `Analysis` から除外
analyzer:
  errors:
    invalid_annotation_target: ignore
